# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'
mod 'puppetlabs/passenger'
mod 'alup/rbenv', :git => 'git@github.com:jlulian38/puppet-rbenv.git'

mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
